# This configuration file is specific for the contextual Forrester test function.
experiment_name: "example_1d_contextual_forrester"

input_dim: 2
lower_bound: [-5.0,-5.0]
upper_bound: [5.0, 5.0]

context_dim: 1

acq_func: "UCB"
max_iter: 100
n_init: 3
log_dir: "~/BO_logs/contextual_forrester_ucb/"
maximize: false
feature_names: ["x1","x2","c1"] #includes the context name also
outcome_names: ["y1"]