# This configuration file is specific for the contextual Forrester test function.
experiment_name: "contextual_hk1d_ucb_ke"

input_dim: 5
lower_bound: [995.0 , 0.001 , 995.0 , 0.0001 , 0.0001]  #Qz_diag(3), R_diag(2)
upper_bound: [1000.0,10.0, 1000.0, 1.0, 1.0] #Qz_diag(3), R_diag(2)

context_dim: 1

acq_func: "UCB"
max_iter: 200
n_init: 4
log_dir: "BO_logs/contextual_hk1d_ucb_ke/"
maximize: false

feature_names: ["Q11","Q22","Q33","R11","R22","ke"] #includes the context name also
outcome_names: ["performance_metric"]
