# This configuration file is specific for the Forrester test function.
experiment_name: "example_1d_forrester"
input_dim: 1
acq_func: "UCB"
lower_bound: [0.0]
upper_bound: [1.0]
max_iter: 30
n_init: 1
log_dir: "BO_logs/forrester_ucb/" #this will be in the base of the workspace
maximize: false
feature_names: ["x1"]
outcome_names: ["y1"]