name: BayesOpt4ROS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:focal

    steps:
    - uses: actions/checkout@v2
    # Ideally we would use a Docker container with ROS already installed
    - name: Set up ROS Noetic 
      uses: ros-tooling/setup-ros@v0.1
      with:
        required-ros-distributions: noetic

    - name: Install Python dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python3-pip
        python3 -m pip install --upgrade pip
        python3 -m pip install flake8 pytest
        if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
        sudo apt-get install python3-empy

    - name: Build catkin workspace
      run: |
        . /opt/ros/noetic/setup.sh
        catkin_make_isolated
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Unittest with pytest
      run: |
        . devel_isolated/setup.sh
        pytest src/bayesopt4ros/test/unit/

    - name: Integration test with rostest
      run: |
        . devel_isolated/setup.sh
        catkin_make_isolated -j1 --catkin-make-args run_tests
        

